# docker image for CLT post deploy tests

FROM vocabai/cloud-language-tools-core:14.0.0

ARG GPG_PASSPHRASE


# this adds any required modules not covered above
COPY requirements.dev.txt ./
RUN pip3 install --no-cache-dir -r requirements.dev.txt && pip3 cache purge

# copy app files
COPY  manual_test_postdeploy.py ./

ENTRYPOINT ["pytest", "manual_test_postdeploy.py"]