#!/bin/bash
set -euxo pipefail

DOCKER_IMAGE=lucwastiaux/cloud-language-tools-postdeploy:latest

docker run \
--env CLOUDLANGUAGETOOLS_CORE_KEY=${CLOUDLANGUAGETOOLS_CORE_KEY} \
--env ANKI_LANGUAGE_TOOLS_BASE_URL=${ANKI_LANGUAGE_TOOLS_BASE_URL} \
--env ANKI_LANGUAGE_TOOLS_API_KEY=${ANKI_LANGUAGE_TOOLS_API_KEY} \
--env ANKI_LANGUAGE_TOOLS_API_VOCAB=${ANKI_LANGUAGE_TOOLS_API_VOCAB} \
--rm -it ${DOCKER_IMAGE}